let chalk = require('chalk');

module.exports = [
  `${chalk.red.bold('All Creative')}`,
  `${chalk.red.bold('All Business')}`,
  `${chalk.red.bold('All Technology')}`,
  `${chalk.red.bold('All Lifestyle')}`,
  "Fine Art",
  "Photography",
  "Graphic Design",
  "Writing",
  "Illustration",
  "Animation",
  "Music Production",
  "UI/UX Design",
  "Film Production",
  "Marketing",
  "Entrepreneurship",
  "Productivity",
  "Freelance",
  "Business Analytics",
  "Finance",
  "Management",
  "Sales",
  "Leadership",
  "Human Resources",
  "Accounting",
  "Web Development",
  "Mobile Development",
  "IT Security",
  "Game Design",
  "Data Science",
  "Product Management",
  "Crafts",
  "Culinary",
  "Health &amp; Wellness",
  "Teaching",
  "Other",
  "Home Business",
  "Gaming",
  "Languages"


]
